# Einspielen der Routing Daemon
# und "restart" von FRR

- hosts: leaf
  name: Configure /etc/frr/daemon
  become: yes
  tasks:
    - copy:
        src: /home/cumulus/ON-02/daemons
        dest: /etc/frr/daemons
      notify:
        - frr_restart
        
- hosts: spine
  name: Configure /etc/frr/daemon
  become: yes
  tasks:
    - copy:
        src: /home/cumulus/ON-02/daemons
        dest: /etc/frr/daemons
      notify:
        - frr_restart


