- name: Check switch network interfaces
  hosts: sw
  tasks:
    - name: NCLU
      register: output
      community.network.nclu:
        commands:
          - show version
          - show interface

    - name: Print Interface Details
      ansible.builtin.debug:
        var: output["msg"]

