- name: Check switch network interfaces
  hosts: sw
  tasks:
    - name: NCLU
      community.network.nclu:
        register: output
        commands:
          - show version
          - show interface

